        </div>
        <div id="footer">
            <a id="back_index" href="index.html">index</a>
            This page is generated by <a href="http://vimwiki.googlecode.com/">Vimwiki</a> <br />
            %time_stamp%
        </div>
    </body>
</html>
